//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseStarter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseStarter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Starter is a portable desktop application for managing local database servers on Windows. It allows you to download, install, start, and stop MySQL, MariaDB, and PostgreSQL as portable instances — without administrator privileges and without Windows services.
        ///All database files are stored in the local user directory and can be completely removed at any time. The configuration is automatically persisted in a JSON file.
        ///The application is aimed at developers who need quick and easy local database ins [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Database Starter.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📥 Install.
        /// </summary>
        public static string ButtonInstall {
            get {
                return ResourceManager.GetString("ButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹ Stop.
        /// </summary>
        public static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Uninstall.
        /// </summary>
        public static string ButtonUninstall {
            get {
                return ResourceManager.GetString("ButtonUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to uninstall {0}?
        ///All data will be deleted!.
        /// </summary>
        public static string ConfirmUninstallMessage {
            get {
                return ResourceManager.GetString("ConfirmUninstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm uninstallation.
        /// </summary>
        public static string ConfirmUninstallTitle {
            get {
                return ResourceManager.GetString("ConfirmUninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initdb.exe / pg_ctl.exe not found..
        /// </summary>
        public static string ErrorInitdbPgctlNotFound {
            get {
                return ResourceManager.GetString("ErrorInitdbPgctlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mysql_install_db.exe not found..
        /// </summary>
        public static string ErrorInstallDbNotFound {
            get {
                return ResourceManager.GetString("ErrorInstallDbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MariaDB initialization failed (Exit {0}):
        ///{1}{2}.
        /// </summary>
        public static string ErrorMariaDbInitFailed {
            get {
                return ResourceManager.GetString("ErrorMariaDbInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mysqld.exe / mariadbd.exe not found..
        /// </summary>
        public static string ErrorMysqldMariadbdNotFound {
            get {
                return ResourceManager.GetString("ErrorMysqldMariadbdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mysqld.exe not found..
        /// </summary>
        public static string ErrorMysqldNotFound {
            get {
                return ResourceManager.GetString("ErrorMysqldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL initialization failed (Exit {0}):
        ///{1}.
        /// </summary>
        public static string ErrorMysqlInitFailed {
            get {
                return ResourceManager.GetString("ErrorMysqlInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg_ctl.exe not found..
        /// </summary>
        public static string ErrorPgCtlNotFound {
            get {
                return ResourceManager.GetString("ErrorPgCtlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL initialization failed (Exit {0}):
        ///{1}{2}.
        /// </summary>
        public static string ErrorPostgresInitFailed {
            get {
                return ResourceManager.GetString("ErrorPostgresInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL start failed (Exit {0}).
        /// </summary>
        public static string ErrorPostgresStartFailed {
            get {
                return ResourceManager.GetString("ErrorPostgresStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string ExpanderLog {
            get {
                return ResourceManager.GetString("ExpanderLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Database Starter.
        /// </summary>
        public static string InfoButtonTooltip {
            get {
                return ResourceManager.GetString("InfoButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string LabelPath {
            get {
                return ResourceManager.GetString("LabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (locked).
        /// </summary>
        public static string LabelVersionLocked {
            get {
                return ResourceManager.GetString("LabelVersionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] ERROR during installation: {1}.
        /// </summary>
        public static string LogInstallError {
            get {
                return ResourceManager.GetString("LogInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] {1} successfully installed..
        /// </summary>
        public static string LogInstallSuccess {
            get {
                return ResourceManager.GetString("LogInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] ERROR during start: {1}.
        /// </summary>
        public static string LogStartError {
            get {
                return ResourceManager.GetString("LogStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] {1} started (PID: {2}, Port: {3})..
        /// </summary>
        public static string LogStartSuccess {
            get {
                return ResourceManager.GetString("LogStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] ERROR during stop: {1}.
        /// </summary>
        public static string LogStopError {
            get {
                return ResourceManager.GetString("LogStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] {1} stopped..
        /// </summary>
        public static string LogStopSuccess {
            get {
                return ResourceManager.GetString("LogStopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] ERROR during uninstallation: {1}.
        /// </summary>
        public static string LogUninstallError {
            get {
                return ResourceManager.GetString("LogUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] {1} uninstalled..
        /// </summary>
        public static string LogUninstallSuccess {
            get {
                return ResourceManager.GetString("LogUninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string MessageDownloading {
            get {
                return ResourceManager.GetString("MessageDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... {0:F1}%.
        /// </summary>
        public static string MessageDownloadingProgress {
            get {
                return ResourceManager.GetString("MessageDownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        public static string MessageExtracting {
            get {
                return ResourceManager.GetString("MessageExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string MessageInitializing {
            get {
                return ResourceManager.GetString("MessageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete!.
        /// </summary>
        public static string MessageInstallComplete {
            get {
                return ResourceManager.GetString("MessageInstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed:
        ///{0}.
        /// </summary>
        public static string MessageInstallFailed {
            get {
                return ResourceManager.GetString("MessageInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running (PID: {0}).
        /// </summary>
        public static string MessageRunningPid {
            get {
                return ResourceManager.GetString("MessageRunningPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start failed:
        ///{0}.
        /// </summary>
        public static string MessageStartFailed {
            get {
                return ResourceManager.GetString("MessageStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string MessageStarting {
            get {
                return ResourceManager.GetString("MessageStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop failed:
        ///{0}.
        /// </summary>
        public static string MessageStopFailed {
            get {
                return ResourceManager.GetString("MessageStopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        public static string MessageStopped {
            get {
                return ResourceManager.GetString("MessageStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string MessageStopping {
            get {
                return ResourceManager.GetString("MessageStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled..
        /// </summary>
        public static string MessageUninstalled {
            get {
                return ResourceManager.GetString("MessageUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation failed:
        ///{0}.
        /// </summary>
        public static string MessageUninstallFailed {
            get {
                return ResourceManager.GetString("MessageUninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string MessageUninstalling {
            get {
                return ResourceManager.GetString("MessageUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (stopped).
        /// </summary>
        public static string StatusInstalled {
            get {
                return ResourceManager.GetString("StatusInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing….
        /// </summary>
        public static string StatusInstalling {
            get {
                return ResourceManager.GetString("StatusInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing… {0:F0} %.
        /// </summary>
        public static string StatusInstallingProgress {
            get {
                return ResourceManager.GetString("StatusInstallingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string StatusNotInstalled {
            get {
                return ResourceManager.GetString("StatusNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running on port {0}.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage portable MySQL, MariaDB &amp; PostgreSQL instances.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Starter – Portable DB Manager.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
